### PR TITLE
Update version of imposm.

### PR DESCRIPTION
**Pull request by francois2metz**
I updated imposm to the current version.

### CODE REVIEW

**Comment by nyurik** [comment]
@francois2metz this (and a few other) changes have been merged into the fork at https://github.com/sophox/import-osm and published as [sophox/import-osm:1.0](https://hub.docker.com/r/sophox/import-osm/) docker container.

You may also need to apply https://github.com/openmaptiles/openmaptiles/pull/675 -- seems like with the new imposm some new data has made it into the tables, thus exposing an SQL error.

**Comment by nyurik** [comment]
Note to everyone. With this update, `CREATE MATERIALIZED VIEW osm_transportation_merge_linestring` fails with `psql:/sql/tileset.sql:1340: ERROR:  Error creating GEOS Coordinate Sequence`.  I am not yet certain what causes this, will explore further.

**Comment by francois2metz** [comment]
I rebased my branch against the new master.

**Comment by francois2metz** [comment]
I had to remove the pgclimb script, has an update from https://github.com/urfave/cli broke the build.

**Comment by nyurik** [comment]
This PR should be moved to the https://github.com/openmaptiles/openmaptiles-tools repo, to the `/imports/osm` dir.  This repo should be archived.

**Comment by francois2metz** [comment]
https://github.com/openmaptiles/openmaptiles-tools/pull/106

**Pull request closed without merging**
